# Generated by Django 3.2.3 on 2022-08-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_date', models.DateTimeField(auto_now_add=True)),
                ('recruit_field', models.CharField(choices=[('study', '스터디'), ('club', '소모임'), ('project', '프로젝트'), ('survey', '설문조사')], default='study', max_length=20)),
                ('recruit_status', models.CharField(choices=[('ongoing', '모집중'), ('end', '모집완료')], default='ongoing', max_length=20)),
                ('recruit_title', models.CharField(max_length=100)),
                ('recruit_period_start', models.DateField()),
                ('recruit_period_end', models.DateField()),
                ('recruit_number', models.IntegerField()),
                ('recruit_meeting', models.CharField(choices=[('offline', '대면'), ('online', '비대면'), ('TBD', '추후결정')], default='offline', max_length=20)),
                ('recruit_content', models.TextField()),
                ('recruit_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('recruit_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hashtag_content', models.CharField(default='#', max_length=30, unique=True)),
                ('hashtag_recruit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='mypage.recruit')),
                ('hashtag_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
