# Generated by Django 4.0.6 on 2022-07-23 13:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='recruit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='recruit',
            name='recruit_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writers', to=settings.AUTH_USER_MODEL),
        ),
    ]
