# Generated by Django 4.1 on 2022-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='recruit_hashtag',
            field=models.ManyToManyField(blank=True, to='mypage.hashtag'),
        ),
    ]
