# Generated by Django 4.1 on 2022-08-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_recruit_recruit_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_date',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_recruit',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_writer',
        ),
    ]
