# Generated by Django 4.0.6 on 2022-07-27 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mypage', '0004_alter_recruit_recruit_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='recruit_hashtag',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_content',
            field=models.CharField(default='#', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_recruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='mypage.recruit'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to=settings.AUTH_USER_MODEL),
        ),
    ]
