# Generated by Django 4.0.6 on 2022-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0005_remove_hashtag_hashtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='recruit_hashtag',
            field=models.ManyToManyField(null=True, to='mypage.hashtag'),
        ),
    ]
