# Generated by Django 4.1.1 on 2022-10-16 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_date', models.DateTimeField(auto_now_add=True)),
                ('question_title', models.CharField(max_length=100)),
                ('question_content', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='questions/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_comment_date', models.DateTimeField(auto_now_add=True)),
                ('question_comment_content', models.CharField(max_length=1000)),
                ('question_comment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comments', to='about.question')),
            ],
        ),
    ]
