# Generated by Django 4.0.6 on 2022-07-25 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0003_alter_comment_comment_recruit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomment_date', models.DateTimeField(auto_now_add=True)),
                ('recomment_content', models.CharField(max_length=1000)),
                ('recomment_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='match.comment')),
                ('recomment_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
