# Generated by Django 4.0.6 on 2022-08-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_recomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_writer_profile',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
