# Generated by Django 4.0.6 on 2022-08-09 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_comment_comment_writer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_writer_profile',
        ),
    ]
